const createCustomer = require('../controllers/customer/createCustomer')
const getCustomer = require('../controllers/customer/getCustomer')
// const { createOrderItem } = require('../controllers/order-items/createOrderItem')
const createOrder = require('../controllers/order/createOrder')
const { getOrderById } = require('../controllers/order/getOrder')
const getOrdersByCustomerId  = require('../controllers/order/getOrderbyCustomerId')
const createProduct = require('../controllers/product/createProduct')
const deleteProduct = require('../controllers/product/deleteProduct')
const getAllProduct = require('../controllers/product/getAllProduct')
const getSingleProduct = require('../controllers/product/getSingleProduct')
const updateProduct = require('../controllers/product/updateProduct')
const ipMiddleware = require('../middlewares/ip')
const { initializeTrans, verifyTrans } = require('../utils/paystack')

const router = require('express').Router()

router.route('/customer').post(createCustomer)
router.route('/customer/:id').get(getCustomer)
router.route('/product').post(createProduct).get(ipMiddleware,getAllProduct)
router.route('/product/:id').get(getSingleProduct).put(updateProduct).delete(deleteProduct)
router.route('/order').post(createOrder)
router.route('/order/:customer_id').get(getOrdersByCustomerId)
router.route('/orders/:id').get(getOrderById)
router.route('/paycheck/:id').post(initializeTrans)
router.route('/paycheckverify/:id').post(verifyTrans)

module.exports = router